# Generated by Django 5.1.3 on 2024-12-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_func', models.BigIntegerField()),
                ('id_horario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_sem', models.CharField(max_length=45)),
                ('hora_inicio', models.CharField(max_length=5)),
                ('hora_fim', models.CharField(max_length=5)),
            ],
        ),
    ]
